name: retroclash-book
version: 0.1.0
category: hardware

custom-setup:
  dependencies:
    - base
    - Cabal
    - clashilator

dependencies:
  - base >= 4.7 && < 5
  - clash-prelude
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

  - retroclash-lib
  - retroclash-sim
  - clash-shake

  - mtl
  - transformers
  - extra
  - array
  - lens
  - sdl2

# Anything that Clash uses by default should go here
default-extensions:
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - ExplicitForAll
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MagicHash
  - MonoLocalBinds
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NoStarIsType
  - NoStrictData
  - NoStrict
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskellQuotes
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators

ghc-options:
  -fexpose-all-unfoldings -fno-worker-wrapper
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver

flags:
  verilator:
    manual: True
    default: False

executables:
  patterns-sim:
    source-dirs: src/vga/patterns/src
    main: Sim.hs

  bounce-verilator:
    source-dirs: src/vga/bounce/src
    main: verilator.hs
    when:
    - condition: flag(verilator)
      then:
        verbatim:
          x-clashilator-top-is: Bounce
      else:
        buildable: false
        
  bounce-state:
    source-dirs: src/vga/bounce/src
    main: simulator.hs

  bounce-state-verilator:
    source-dirs: src/vga/bounce/src
    main: verilator.hs
    when:
    - condition: flag(verilator)
      then:
        verbatim:
          x-clashilator-top-is: BounceState
      else:
        buildable: false

  etcher-verilator:
    source-dirs: src/vga/etcher/src
    main: verilator.hs
    when:
    - condition: flag(verilator)
      then:
        verbatim:
          x-clashilator-top-is: Etcher
      else:
        buildable: false

